name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          #- name: Docker Login
          #  uses: docker/login-action@v2
          #  with:
          #    registry: us-east1-docker.pkg.dev/codepros/codepros
      - name: Configure Docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev
      - name: Docker Build and Push
        run: docker build --push -t us-east1-docker.pkg.dev/codepros/codepros/vault:${GITHUB_REF##*/} ./0.X/
