name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: us-east1-docker.pkg.dev/codepros/codepros
          username: ${{ secrets.GCP_USER }}
          password: ${{ secrets.GCP_PAT }}
      - name: Docker Build and Push
        run: docker build --push -t us-east1-docker.pkg.dev/codepros/codepros/vault:${{ github.ref }} ./0.X/
